language: go
go:
  - release
  - tip
install:
  - go get -d -t -v ./...
  - ./.travis/get_ci_vet.sh
  - ./.travis/get_ci_cover.sh  
  - go get -v github.com/GeertJohan/fgt
  - go get -v golang.org/x/lint/golint
script:
  - export PATH=$PATH:$HOME/gopath/bin
  - go vet
  - fgt golint .
  - go test -v -covermode=count -coverprofile=profile.cov
after_success:
  - go get -v github.com/mattn/goveralls
  - goveralls -coverprofile=profile.cov -service=travis-ci
